In [1]:
import pandas as pd
import numpy as np
from rbfnn import RBFNN

In [2]:
data = pd.read_csv('modified_data_temp_df.csv', index_col=0)
data

T-1  T-24   H-1  H-24  Season     T
0     62.0  65.0  89.0  90.0     1.0  65.0
1     65.0  65.0  90.0  90.0     1.0  65.0
2     65.0  65.0  90.0  90.0     1.0  65.0
3     65.0  78.0  90.0  49.0     1.0  78.0
4     78.0  78.0  48.0  49.0     1.0  78.0
...    ...   ...   ...   ...     ...   ...
8731  67.0  69.0  92.0  88.0     1.0  67.0
8732  67.0  69.0  92.0  88.0     1.0  67.0
8733  67.0  65.0  92.0  94.0     1.0  65.0
8734  65.0  65.0  94.0  94.0     1.0  65.0
8735  65.0  65.0  94.0  94.0     1.0  65.0

[8736 rows x 6 columns]

In [3]:
x_data = data[data.columns[:5]]
x_data

T-1  T-24   H-1  H-24  Season
0     62.0  65.0  89.0  90.0     1.0
1     65.0  65.0  90.0  90.0     1.0
2     65.0  65.0  90.0  90.0     1.0
3     65.0  78.0  90.0  49.0     1.0
4     78.0  78.0  48.0  49.0     1.0
...    ...   ...   ...   ...     ...
8731  67.0  69.0  92.0  88.0     1.0
8732  67.0  69.0  92.0  88.0     1.0
8733  67.0  65.0  92.0  94.0     1.0
8734  65.0  65.0  94.0  94.0     1.0
8735  65.0  65.0  94.0  94.0     1.0

[8736 rows x 5 columns]

In [4]:
y_data = data[['T']]
y_data

T
0     65.0
1     65.0
2     65.0
3     78.0
4     78.0
...    ...
8731  67.0
8732  67.0
8733  65.0
8734  65.0
8735  65.0

[8736 rows x 1 columns]

In [5]:
from sklearn.preprocessing import MinMaxScaler

x_scalar = MinMaxScaler()
x_scalar.fit(x_data)
x_data_scaled = x_scalar.fit_transform(x_data)
x_data_scaled

array([[0.20689655, 0.25862069, 0.85227273, 0.86363636, 0.5       ],
       [0.25862069, 0.25862069, 0.86363636, 0.86363636, 0.5       ],
       [0.25862069, 0.25862069, 0.86363636, 0.86363636, 0.5       ],
       ...,
       [0.29310345, 0.25862069, 0.88636364, 0.90909091, 0.5       ],
       [0.25862069, 0.25862069, 0.90909091, 0.90909091, 0.5       ],
       [0.25862069, 0.25862069, 0.90909091, 0.90909091, 0.5       ]])

In [6]:
y_scalar = MinMaxScaler()
y_scalar.fit(y_data)
y_data_scaled = y_scalar.fit_transform(y_data)
y_data_scaled

array([[0.25862069],
       [0.25862069],
       [0.25862069],
       ...,
       [0.25862069],
       [0.25862069],
       [0.25862069]])

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_data_scaled, y_data_scaled, test_size=0.33, random_state=42)

In [8]:
rbf = RBFNN(X=X_train,
      y=y_train,
      X_test=X_test,
      y_test=y_test,
      n_hidden_neurons=4,
      width_factor=2)


Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2023-02-25 14:28:43.488037: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-02-25 14:28:43.488748: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [9]:
rbf.fit(epochs=10, metrics=['mae'])

Epoch 1/10


2023-02-25 14:29:22.226731: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-02-25 14:29:22.611321: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


183/183 [==============================] - ETA: 0s - loss: 0.0134 - mae: 0.0829

2023-02-25 14:29:24.282329: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


183/183 [==============================] - 2s 10ms/step - loss: 0.0134 - mae: 0.0829 - val_loss: 0.0085 - val_mae: 0.0704
Epoch 2/10
183/183 [==============================] - 1s 7ms/step - loss: 0.0085 - mae: 0.0716 - val_loss: 0.0079 - val_mae: 0.0670
Epoch 3/10
183/183 [==============================] - 1s 8ms/step - loss: 0.0092 - mae: 0.0743 - val_loss: 0.0103 - val_mae: 0.0819
Epoch 4/10
183/183 [==============================] - 1s 8ms/step - loss: 0.0086 - mae: 0.0720 - val_loss: 0.0079 - val_mae: 0.0677
Epoch 5/10
183/183 [==============================] - 1s 8ms/step - loss: 0.0085 - mae: 0.0714 - val_loss: 0.0082 - val_mae: 0.0680
Epoch 6/10
183/183 [==============================] - 2s 9ms/step - loss: 0.0088 - mae: 0.0730 - val_loss: 0.0095 - val_mae: 0.0782
Epoch 7/10
183/183 [==============================] - 1s 8ms/step - loss: 0.0086 - mae: 0.0721 - val_loss: 0.0096 - val_mae: 0.0751
Epoch 8/10
183/183 [==============================] - 1s 7ms/step - loss: 0.0083 - mae

In [13]:
x = np.array([65, 67, 90, 87, 1])
rbf.predict(x)

1/1 [==============================] - 0s 85ms/step


2023-02-25 14:30:10.245627: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[0.59663445]], dtype=float32)

In [14]:
import joblib as jbl

metadata = jbl.load("Metadata_N_4_P_2_bs_32.jbl")

In [15]:
metadata

{'neurons': 4,
 'centers': array([[ 5.56940831e-01,  5.56857807e-01,  6.31767109e-01,
          6.32323435e-01,  1.00000000e+00],
        [ 5.53207920e-01,  5.53962827e-01,  7.17550442e-01,
          7.18276753e-01, -1.38777878e-15],
        [ 6.83356184e-01,  6.77484026e-01,  2.83221374e-01,
          2.85668008e-01,  7.70442611e-01],
        [ 3.56442408e-01,  3.57969617e-01,  7.48083987e-01,
          7.41329378e-01,  5.00000000e-01]]),
 'sigma': array([0.40303985, 0.40533549, 0.40303985, 0.40533549]),
 'batch_size': 32,
 'lr': 0.1,
 'loss_fn': keras.losses.MeanSquaredError}

In [17]:
rbf.predict(x, 'Metadata_N_4_P_2_bs_32.jbl', 'RBF_ANN_model_bs_32_N_4_P_2.h5')

1/1 [==============================] - 0s 33ms/step


2023-02-25 14:30:21.928302: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[0.59663445]], dtype=float32)